# Generated by Django 4.2.5 on 2023-11-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
