# Generated by Django 4.2.5 on 2023-11-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_student_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfoModel',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('payment', models.IntegerField()),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherInfoModel',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('salary', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
